### ISSUE TITLE
Potential 7.10 incompatibility

### ISSUE THREAD

**Issue by LarsS88** [Open-CSP/WikiSearch#52] opened 2024-07-12 08:14 UTC
Hello,

We have installed WIkiSearch 8.0.0 on a server with Elasticsearch 7.10.
The net result is an endless spinner when you attempt to perform a search.
I say 'spinner'; of course in WikiSearchFront that means a loading bar, but nonetheless, the search is not completing.

We believe this problem might be in the back-end, WikiSearch, rather than Front.
Could you please look into this?
And let me know, even if I'm totally wrong in these assumptions,.

A testcase, for your convenience, can be found on true03, under the domain name nwsweco and you know the rest...

**Comment by marijnvanwezel** [comment] 2024-07-12 08:24
Are you using `master`?

**Comment by marijnvanwezel** [comment] 2024-07-12 08:27
Also, please provide the API response from the backend with `$wgShowExceptionDetails` and `$wgWikiSearchEnableDebugMode` both set to true while doing an empty search. The response can be found in the Network tab of your browser.

**Comment by bertrandgorge** [comment] 2024-07-12 16:01
I usually have that when the configuration of WikiSearch / WikiSearchFront on the page is wrong. I'd suggest testing a very minimal configuration to see if it works, then adding more stuff progressively...

**Comment by marijnvanwezel** [comment] 2024-07-17 09:01
This issue is not related to WikiSearch, but to Semantic MediaWiki. It is caused by the `base query` containing a conjunction of a negation (e.g. `[[A::!B]] [[C::!D]]`). This query is then converted by WikiSearch, but using SMW, to an invalid ElasticSearch query.

I reported this issue in Semantic MediaWiki (SemanticMediaWiki/SemanticMediaWiki#5651) and created a fix for it (SemanticMediaWiki/SemanticMediaWiki#5652) a while back. The fix has not been merged yet, but to make use of it already, you can use [this branch](https://github.com/WikibaseSolutions/SemanticMediaWiki/tree/5651-ask-query-with-a-conjunction-of-negations-fails-when-using-elasticsearch).

**Closed by marijnvanwezel** 2024-07-17 09:01 UTC
